import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <figure className="bg-slate-100 rounded-xl p-8 dark:bg-slate-800">
        <div className="pt-6 space-y-4">
          <blockquote>
            <p className="text-lg font-medium">“Tailwind CSS is the only framework that I&apos;ve seen scale on large teams. It&apos;s easy to customize, adapts to any design, and the build size is tiny.”</p>
          </blockquote>
          <figcaption>
            <div>Sarah Dayan</div>
            <div>Staff Engineer, Algolia</div>
          </figcaption>
        </div>
      </figure>
    </div>
  );
};

export default Home;
